### ISSUE TITLE
switch to Kerko

### ISSUE THREAD

**Issue by adammwilson** [BioSCape-io/BioSCape-publications#5]
Just saw this https://github.com/whiskyechobravo/kerkoapp?tab=readme-ov-file

Could this be switched to that format instead of the table (running with github actions)?  It's got some nice features!

**Comment by Luna5ama** [comment]
That is a full-stack web app. It will require a server to be constantly running to deploy. In contrast, the current solution is just a simple JavaScript-based front end only, it doesn't require a server running a backend server application. That is what makes it possible to deploy using GitHub pages. If you can get a server or some kind of cloud hosting service for deployment, we could switch to Kerko.

**Comment by adammwilson** [comment]
I see.  I didn't realize it needed a server...

**Comment by adammwilson** [comment]
closing
