### ISSUE TITLE
More accurate date parsing

### ISSUE THREAD

**Issue by adammwilson** [BioSCape-io/BioSCape-publications#6]
Can we update the date field to just a 4-digit year more accurately?  Right now it's a mixture of different formats so the sort doesn't work.  

Also please default sort on year so the most recent are at the top.

**Comment by adammwilson** [comment]
Hey Luna - can you work on this?

**Comment by Luna5ama** [comment]
Hi Adam, I was waiting for the work-study appointment setup but I think I could start working immediately and fill in the times later.
